### ISSUE TITLE
Evaluation code for Key points, RTE and RRE

### ISSUE THREAD

**Issue by uniBruce** [ispc-lab/PointINet#2]
HI, thanks for the amazing work.

I am wondering if you could kindly provide the evaluation code for the results in Table 3~5, which means Key points detection, RTE and RRE.

**Comment by FanLu97** [comment]
@uniBruce Hi, thanks for your interest! Due to that the evaluation of keypoints detection and multi-frame ICP is not the main evaluation metric of this paper, we have not organized the code of this part. However, the implementation is trivial with the help of PCL (Point cloud library). If you have any questions when implementing the evaluation of this part, please contact me via email lufan@tongji.edu.cn.
